### ISSUE TITLE
nan value in Hypothesis Testing

### ISSUE THREAD

**Issue by emauryg** [KarchinLab/SCHISM#5]
I'm getting a nan value on the Hypothesis testing while running the Step-Through mode. It seems that if the s.d. of some samples were 0 in the  .cellularity file after using the prepare_for_hypothesist_test command. Once I added a small s.d. the issue resolved. Not sure if that's the appropriate course of action though. 

Is this a bug?

**Comment by Niknafs** [comment]
Dear Eduardo,
Thank you for reporting this issue. This is not a bug, but the expected outcome in a case where the standard deviation of cellularity value is zero. More specifically, the test statistic in SCHISM is essentially a summation of terms, each of which is normalized by the standard deviation. The reported standard deviations help evaluate the significance of an observed deviation from the lineage precedence rule, and are therefore essential in the model. It might be useful to think about why you have zero standard deviations in the first place. I will be glad to help if you would like to share more details.
Best,
Noushin

**Comment by emauryg** [comment]
Dear Noushin, 
Thank you for the quick reply. I'm not sure why the standard deviation is zero. I clustered my mutations and calculated the cellular prevalence of each mutation using PyClone and then created the .clusterEstimates.tsv and mutation-to-cluster.tsv following the format from the tutorial E2. No s.d. until this point had a value of zero.  I then followed the Step-through protocol as per the example and got nans in Hypothesis testing. After I added a small s.d. I continued through the rest of the analysis, and ended up with the message below after trying to find the consensus tree. 


```
Traceback (most recent call last):
  File "/home/eam63/anaconda2/bin/runSchism", line 155, in <module>
    main()
  File "/home/eam63/anaconda2/bin/runSchism", line 152, in main
    args.func(args)
  File "/home/eam63/anaconda2/lib/python2.7/site-packages/SCHISM/GA.py", line 136, in generate_consensus_tree
    plot_consensus_tree(args)
  File "/home/eam63/anaconda2/lib/python2.7/site-packages/SCHISM/visualize.py", line 326, in plot_consensus_tree
    root = list(set(vertices) - set(zip(*edges)[1]))[0]
IndexError: list index out of range
```

**Comment by Niknafs** [comment]
Thank you for sharing the details. I think I have an idea what is going on. If you report the same cellularity value for all mutations in a cluster, then the program's of the cluster cellularity standard deviation (variation of cellularity within a cluster) will be zero.
In case of your setup, If you have identified clusters and their cellularity value using PyClone, the most straightforward approach is to use one representative mutation from each cluster in the input. In the mutation to cluster assignment file, you can have a one-to-one mapping from those representative mutations to clusters. This trick should get around the issue of zero standard deviation above.

**Comment by emauryg** [comment]
I see. That helps taking care of the nan issue. However, it does not help addressing the vertices issue below. 
`Traceback (most recent call last):
  File "/home/eam63/anaconda2/bin/runSchism", line 155, in <module>
    main()
  File "/home/eam63/anaconda2/bin/runSchism", line 152, in main
    args.func(args)
  File "/home/eam63/anaconda2/lib/python2.7/site-packages/SCHISM/GA.py", line 136, in generate_consensus_tree
    plot_consensus_tree(args)
  File "/home/eam63/anaconda2/lib/python2.7/site-packages/SCHISM/visualize.py", line 326, in plot_consensus_tree
    root = list(set(vertices) - set(zip(*edges)[1]))[0]
IndexError: list index out of range
`

**Comment by Niknafs** [comment]
Thanks for reminding me about the second issue.
Without seeing the intermediate files, it is hard for me to guess why you are encountering an issue in the line highlighted. The goal here is to identify the root of the tree, i.e. the only node in the tree that does not have a parent [zip(*edges)[1]]. Have you reviewed the GA outputs (top scoring trees)?

**Comment by emauryg** [comment]
Alright so I'm using the average cluster cellularity as the input for SCHISM, rather than just selecting a representative mutation and that seems to produce trees. Is this approach valid?

**Comment by Niknafs** [comment]
Yes. This is a valid approach.

**Comment by nihilee** [comment]
@Niknafs dear developer, I came up with the same problem when using SCHISM, my GA.consensusTree looks like this:
parent   child   frequency   label
------   -----   ---------   -------
0        1       0.2         125/625
0        2       0.2         125/625
0        3       0.2         125/625
0        4       0.2         125/625
1        0       0.2         125/625
1        2       0.2         125/625
1        3       0.2         125/625
1        4       0.2         125/625
2        0       0.2         125/625
2        1       0.2         125/625
2        3       0.2         125/625
2        4       0.2         125/625
3        0       0.2         125/625
3        1       0.2         125/625
3        2       0.2         125/625
3        4       0.2         125/625
4        0       0.2         125/625
4        1       0.2         125/625
4        2       0.2         125/625
4        3       0.2         125/625
it does not have a parent, how can I fix it?
